[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#2ECBFF"
backgroundColor = "#1B1C1E"
secondaryBackgroundColor = "#25262A"
textColor = "#F2F4F7"
font = "sans serif"
